site_name: Fazendo Ciência

nav:
  - Inicial: index.md
  - Introdução:
    - Ciência: 01-introducao/introducao-ciencia.md
    - Artigos científicos: 01-introducao/introducao-artigos.md
    - Revistas: 01-introducao/introducao-revistas.md
    - Pesquisa academica: 01-introducao/introducao-pesquisa.md
    - Construir Conhecimento: 01-introducao/introducao-construcao.md
    - Ferramentas e Recursos: 01-introducao/introducao-ferramentas.md
  - Sobre: 
    - Como contribuir: contribuir.md
    - Política de colaboração: contribuir-politica.md
    - Planejamento educacional: apoio/planejamento-educacional.md
    - Autores: sobre.md

extra:
  generator: false

theme:
  language: pt-BR
  name: material
  
  features:
    - navigation.expand
    # - navigation.tabs.sticky

  # icon:
  #   logo: material-book-education
  #   previous: fontawesome/solid/angle-left
  #   next: fontawesome/solid/angle-right
  font:
    text: Roboto
    code: JetBrains Mono
    
  palette:
    # # Palette toggle for automatic mode
    # - media: "(prefers-color-scheme)"
    #   toggle:
    #     icon: material/brightness-auto
    #     name: Modo claro

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: green
      toggle:
        icon: material/lightbulb
        name: Modo noturno

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: green
      toggle:
        icon: material/lightbulb-outline
        name: Modo claro

#theme: readthedocs

markdown_extensions:
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

  - pymdownx.tasklist
  - pymdownx.highlight

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

  - tables

  - attr_list
  - md_in_html

  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

